version: '3.8'

services:
  backend:
    build: ./back
    container_name: normativas-backend
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "5000:5000"

  frontend:
    build: ./normativas-app
    container_name: normativas-frontend
    ports:
      - "4808:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: normativas-db
    environment:
      POSTGRES_DB: normativas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Asdf123.
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./basename.sql:/docker-entrypoint-initdb.d/basename.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: